### ISSUE TITLE
Docker-compose first block of code (clean server)

### ISSUE THREAD

**Issue by pwalczysko** [ome/training-docker#3]
The block of code in the 

docker-compose.yml:

```
services:

  omeroserver:
    image: "openmicroscopy/omero-server:5"
    environment:
      - CONFIG_omero_db_host=omero
      - CONFIG_omero_db_user=omero
      - CONFIG_omero_db_pass=SeCrEtPaSsWoRd
      - CONFIG_omero_db_name=omero
      - ROOTPASS=omero-root-password
    networks:
      - omero-network
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero-volume:/OMERO"

networks:
  omero-network:

volumes:
  omero-volume:
```

The following cmd 

```
docker compose -f docker-compose.yml up
```

does NOT spin up a running OMERO.server. Instead:

```
....

omeroserver-1  | Thu Jun 12 09:58:45 AM UTC 2025 - waiting for postgres:5432...
omeroserver-1  | Thu Jun 12 09:58:46 AM UTC 2025 - waiting for postgres:5432...
omeroserver-1  | Thu Jun 12 09:58:47 AM UTC 2025 - waiting for postgres:5432...
omeroserver-1  | Thu Jun 12 09:58:48 AM UTC 2025 - waiting for postgres:5432...
omeroserver-1  | Thu Jun 12 09:58:49 AM UTC 2025 - waiting for postgres:5432...
omeroserver-1  | Thu Jun 12 09:58:50 AM UTC 2025 - postgres:5432 still not reachable, giving up
omeroserver-1 exited with code 1
```

imho, there is a hard-coded assumption that the postgres has to be on 5432 and, even if the postgres is inside the server container, the server gives up.
